### PR TITLE
Twitter Clone 

### PR DESCRIPTION
**Pull request by tzvaita**
This project consisted of building a CSS framework. We accomplished that using the SASS preprocessor. The main key areas were:

- building a 12 column grid framework
- creating classes which can be referenced when building a website
- create a responsive framework with rows and columns
- error validation with w3c and stickler

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Framework file is missing.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: great!
### But css file with framework is not present, so I can't check if all requirements are met. Please add framework file to your project and submit for review again.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Team!

### Nice job! Project looks! :+1: 

But first of all let's fix the next problems and we can move on.
### Project Specification Shortcut (requirements from Odin)
#### Responsiveness
* Breakpoints
screenshot from Pathwright

## \[OPTIONAL\]

* The CSS files define separate classes for float left, right and clearing the floats
* The CSS files define separate classes to change the position property of an element to relative, absolute or fixed
* At least ten different classes to set the background and text colors of an element
* Classes to horizontally align text to the left, right or center
* At least five classes to set the font size of an element
* Three classes to set the font weight of an element (bold, normal, medium)
* The CSS files define separate classes for border top, bottom, left, right, all border
* The border should span from 0 to 1rem
* The border should have classes for making box round
* The border should have a class defined to transform a box into a circle


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes

**Comment by didymus707** [comment]
changes made

**Review by nikasulo — APPROVED** [review]
# Great wor @didymus707 and @tzvaita!
Please merge and go! :rocket:

**Comment by didymus707** [comment]
Thanks a lot, brother

**Pull request merged**
